#!/bin/bash

set -e  # exit on error

# i3 config
echo "🔗 Linking i3 config..."
mkdir -p ~/.config/i3
ln -sf "$HOME/cg-i3dotfiles/config/i3/config" ~/.config/i3/config

# polybar config
echo "🔗 Linking polybar config..."
mkdir -p ~/.config/polybar
ln -sf "$HOME/cg-i3dotfiles/config/polybar/"* ~/.config/polybar/

# app launcher config
echo "🔗 Linking rofi config..."
mkdir -p ~/.config/rofi
ln -sf "$HOME/cg-i3dotfiles/config/rofi/"* ~/.config/rofi/

# i3lock config
echo "🔗 Linking i3lock config..."
mkdir -p ~/.config/i3lock
ln -sf "$HOME/cg-i3dotfiles/config/i3lock/"* ~/.config/i3lock/

# fish config
echo "🔗 Linking fish config..."
mkdir -p ~/.config/fish
ln -sf "$HOME/cg-i3dotfiles/config/fish/"* ~/.config/fish

# kitty config
echo "🔗 Linking kitty config..."
mkdir -p ~/.config/kitty
ln -sf "$HOME/cg-i3dotfiles/config/kitty/"* ~/.config/kitty

# change shell
chsh -s /bin/fish

# nvim config
echo "🔗 Linking Neovim config..."
mkdir -p ~/.config/nvim
# Remove existing nvim config to avoid conflicts
rm -rf ~/.config/nvim/*
ln -sf "$HOME/cg-i3dotfiles/config/nvim/"* ~/.config/nvim/

echo "✅ All configs linked."
